name: Build Tomcat

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - name: Check out tomcat-users.xml
        uses: actions/checkout@v4
        # if you don't declare repository for checkout action, default will be current reository

      - name: List project files and java version
        run: |
          pwd
          ls -ltr
          java -version



      - name: Checkout Apache tomcat
        uses: actions/checkout@v4
        with:
          repository: apache/tomcat  # repository name with owner
          ref: master
          path: ./tomcat

      - name: Setup Java 9
        uses: actions/setup-java@v1
        with:
          java-version: '16'
          java-package: jdk
          architecture: x64

      - name: List project files and java version
        run: |
          pwd
          ls -ltr
          java -version
          
      - name: Copy tomcat-users.xml into Tomcat configuration directory
        run: cp -v tomcat-users.xml ./tomcat/conf/tomcat-users.xml

      - name: Compile Tomcat
        run: |
          cd ./tomcat
          ant
